### ISSUE TITLE
On/Off Indicator contrary to Ardour

### ISSUE THREAD

**Issue by thoth-amon** [brummer10/ToneTwistPlugs#1]
Getting this with all the tonetwist plugins. When the plugin is on (visually and audibly), it looks in ardour to be off and visa versa. Picture attached.

![Screenshot_20231004_172822](https://github.com/brummer10/ToneTwistPlugs/assets/78971907/98ef1609-befc-4c6b-baa0-b200ca733871)

**Comment by brummer10** [comment]
Ups, yes, will fix it very soon.

**Comment by brummer10** [comment]
A new release is out, the issue you reported should be fixed now.
https://github.com/brummer10/ToneTwistPlugs/releases/tag/v0.5

**Comment by thoth-amon** [comment]
Confirmed, the issue is fixed
