### ISSUE TITLE
GUI breaks when above a certain size

### ISSUE THREAD

**Issue by thoth-amon** [brummer10/ToneTwistPlugs#3]
Happening across multiple plugins and formats. Picture attached.  They open like the picture from the start in Ardour but I ran the standalone, which opens smaller and loks fine but as soon as I increase the size

![Screenshot_20231005_165502](https://github.com/brummer10/ToneTwistPlugs/assets/78971907/788ea47a-9cdd-4aa2-b02a-37fe83a88165)

**Comment by brummer10** [comment]
Ups, Yea I see. 
I've now pushed a fix for that to the repository, but to check it out you need to build yourself from git. 
I'll wait a bit before I pushed a new release.

**Comment by brummer10** [comment]
A new release is out, the issue you reported  should be fixed now.
https://github.com/brummer10/ToneTwistPlugs/releases/tag/v0.6

**Comment by thoth-amon** [comment]
Can confirm it's fixed, thanks.
