### ISSUE TITLE
post new clap binaries

### ISSUE THREAD

**Issue by RustoMCSpit** [brummer10/ToneTwistPlugs#5]

**Comment by brummer10** [comment]
https://github.com/brummer10/ToneTwistPlugs/actions/runs/9154811475#artifacts

**Comment by RustoMCSpit** [comment]
> https://github.com/brummer10/ToneTwistPlugs/actions/runs/9154811475#artifacts

could you post those in releases???

**Comment by brummer10** [comment]
No. The link address change with every push I made to the repository. 
That are so called nightly builds, reflect the latest state of the repository as binary. 
It could be easy access via the "Actions" tab of the repository.

**Comment by RustoMCSpit** [comment]
okay well could you add that in the readme then?
